package com.cosnet.appui.android.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "COSPLAY".
 */
@Entity
public class Cosplay {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String cosplay_name;
    private String cosplay_serie;
    private java.util.Date start_date;
    private java.util.Date due_date;
    private String status;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated(hash = 1385845649)
    public Cosplay() {
    }

    public Cosplay(Long id) {
        this.id = id;
    }

    @Generated(hash = 1130261285)
    public Cosplay(Long id, @NotNull String cosplay_name, String cosplay_serie, java.util.Date start_date, java.util.Date due_date,
            String status) {
        this.id = id;
        this.cosplay_name = cosplay_name;
        this.cosplay_serie = cosplay_serie;
        this.start_date = start_date;
        this.due_date = due_date;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getCosplay_name() {
        return cosplay_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCosplay_name(@NotNull String cosplay_name) {
        this.cosplay_name = cosplay_name;
    }

    public String getCosplay_serie() {
        return cosplay_serie;
    }

    public void setCosplay_serie(String cosplay_serie) {
        this.cosplay_serie = cosplay_serie;
    }

    public java.util.Date getStart_date() {
        return start_date;
    }

    public void setStart_date(java.util.Date start_date) {
        this.start_date = start_date;
    }

    public java.util.Date getDue_date() {
        return due_date;
    }

    public void setDue_date(java.util.Date due_date) {
        this.due_date = due_date;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
