package com.cosnet.appui.android.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cosnet.appui.android.db.Cosplay;

import com.cosnet.appui.android.db.CosplayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cosplayDaoConfig;

    private final CosplayDao cosplayDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cosplayDaoConfig = daoConfigMap.get(CosplayDao.class).clone();
        cosplayDaoConfig.initIdentityScope(type);

        cosplayDao = new CosplayDao(cosplayDaoConfig, this);

        registerDao(Cosplay.class, cosplayDao);
    }
    
    public void clear() {
        cosplayDaoConfig.clearIdentityScope();
    }

    public CosplayDao getCosplayDao() {
        return cosplayDao;
    }

}
