name: .NET Core

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, develop]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build with dotnet
        run: dotnet build ./CosNet.API/CosNet.API.csproj --configuration Release

  build-idp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build with dotnet
        run: dotnet build ./CosNet.IDP/CosNet.IDP.csproj --configuration Release

  build-webui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: cd ./CosNet.WebUI && npm install

      - name: Build with dotnet
        run: dotnet build ./CosNet.WebUI/CosNet.WebUI.csproj --configuration Release
